name: create txt and archive and push

on:
  push:
    branches:
      - master
    paths:
      - "trigger/**"
  pull_request:
    paths:
      - "trigger/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
#    permissions: write-all
    steps:
      - name: check branch name
        run: |
               echo ${{ github.head_ref }} 
               echo ${{ github.ref }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: create index.html
        run: |
          touch publish/index.html
          echo "hello" > publish/index.html
          date >> publish/index.html

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-archive
          path: publish/index.html
          retention-days: 5

      #masterへのマージでない場合はpublish/index.htmlをfeature-gh-pagesで公開
      - name: publish docs to feature github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ success() && github.ref != 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: feature-gh-pages
          publish_dir: ./publish

      - name: change gh-pages source to feature
        if: ${{ success() && github.ref != 'refs/heads/master' }}
        run: |
          curl \
            -X PUT \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/shota-osumi/test/pages \
            -d '{"source":{"branch":"feature-gh-pages","path":"/"}}'

      #masterへのマージである場合はpublish/index.htmlをgh-pagesで公開
      - name: publish docs to stable github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./publish

      - name: change gh-pages source to stable
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          curl \
            -X PUT \
            -H 'Accept: application/vnd.github+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            https://api.github.com/repos/shota-osumi/test/pages \
            -d '{"source":{"branch":"gh-pages","path":"/"}}'