name: create txt and archive and push

#on: [push]
on: 
  pull_request:
    path:
      - "test/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: check branch name
        run: |
               echo ${{ github.head_ref }} 
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: create index.html
        run: |
          touch test/index.html
          echo "hello" > test/index.html
          date >> test/index.html
      # - name: replace file
      #   run: |  
      #           ls -la build/html/
      #           rm build/html/*
      #           cp test/index.html build/html/index.html
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-archive
          path: test/index.html
          retention-days: 5
      # - name: git push
      #   run: |
      #           git config --global user.name "${GITHUB_ACTOR}"
      #           git config --global user.email "${GITHUB_ACTOR}"
      #           #                git pull origin HEAD:${{github.head_ref}}
      #           git branch
      #           git status
      #           git add .
      #           git commit -m "action update"
      #           git push

      #masterへのマージでない場合はtest/index.htmlをdevにpushしてbuild/html/index.htmlをgh-pagesで公開
      - name: publish docs to github pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ success() && github.ref != 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dev
          destination_dir:  build/html/
          publish_dir: ./test

      # #masterへのマージである場合はtest/index.htmlをdevにpushしてbuild/html/index.htmlをgh-pagesで公開
      # - name: publish docs to github pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ success() && github.ref != 'refs/heads/master' }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: dev
      #     destination_dir:  build/html/
      #     publish_dir: ./test