name: create txt and archive and push

on: 
  pull_request:
    path:
      - "test/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: create test.txt
        run: |
          touch test/test.txt
          echo "hello" > test/test.txt
          date >> test/test.txt
      - name: replace file
        run: |  
                ls -la build/html/
                rm build/html/*
                cp test/test.txt build/html/hello.txt
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-archive
          path: build/html/hello.txt
          retention-days: 5
      - name: git push
        run: |
                git config --global user.name "${GITHUB_ACTOR}"
                git config --global user.email "${GITHUB_ACTOR}"
                git add .
                git commit -m "action update"
                git push origin HEAD:${{ github.head_ref }}
